version: '3.5'
services:

  registry:
    image: registry:2
    ports: ["5000:5000"]
    restart: always
    volumes:
      - registry:/var/lib/registry
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true

volumes:
  registry:
