version: '3.5'
services:
  jupyter:
    image: ${USERNAME}/datalabframework:latest
    command: >
      sh -c "cd /home/jovyan/datalabframework &&
             make develop &&
             cd /home/jovyan &&
             start.sh jupyter lab"
    volumes:
      - ${PROJECTDIR}:/home/jovyan/demo
      - ./conf:/conf
      - ${ROOTPATH}/datalabframework:/home/jovyan/datalabframework
    ports: ["8888:8888"]
    environment:
      SPARK_CONF_DIR: /conf
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
