version: '3.5'
services:
  postgres:
    image: postgres
    volumes:
      # - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres/data:/docker-entrypoint-initdb.d
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
