version: '3.5'
services:
  jupyter:
    image: ${REGISTRY}/${USERNAME}/${IMAGENAME}:${IMAGETAG}
    command: cd /home/jovyan/demo && start.sh jupyter lab
    volumes:
      - ${PROJECTDIR}:/home/jovyan/demo
      - ./conf:/conf
    ports: ["8888:8888"]
    environment:
      SPARK_CONF_DIR: /conf
    networks:
     - datalabframework

networks:
  datalabframework:
    name: datalabframework
    driver: bridge
    external: true
